services:
  # 1. Base de Datos
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=libnamic_user
      - POSTGRES_PASSWORD=libnamic_password
      - POSTGRES_DB=inventario_db
    ports:
      - "5432:5432"

  # 2. API (Backend)
  web:
    build: ./backend  # <-- Apunta a la subcarpeta backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app # <-- Sincroniza la subcarpeta
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://libnamic_user:libnamic_password@db/inventario_db
    depends_on:
      - db

  # 3. Interfaz (Frontend)
  frontend:
    build: ./frontend # <-- Apunta a la subcarpeta frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita conflictos de librerÃ­as entre Windows y Docker
    ports:
      - "5173:5173"
    depends_on:
      - web

volumes:
  postgres_data: