services:
  # 1. Servicio de Base de Datos (PostgreSQL)
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=libnamic_user
      - POSTGRES_PASSWORD=libnamic_password
      - POSTGRES_DB=inventario_db
    ports:
      - "5432:5432"

  # 2. Tu API (FastAPI)
  web:
    build: ./backend  # <-- Antes era ".", ahora es "./backend"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app # <-- Antes era ".:/app", ahora es "./backend:/app"
    ports:
      - "8000:8000"
    environment:
      # IMPORTANTE: AquÃ­ conectamos con el servicio 'db'
      - DATABASE_URL=postgresql://libnamic_user:libnamic_password@db/inventario_db
    depends_on:
      - db

volumes:
  postgres_data: